
    import './styles.scoped.css';
    export default {
  "root": "awsui_root_1xupv_ghw6u_114",
  "wizard": "awsui_wizard_1xupv_ghw6u_127",
  "refresh": "awsui_refresh_1xupv_ghw6u_127",
  "small-container": "awsui_small-container_1xupv_ghw6u_134",
  "navigation": "awsui_navigation_1xupv_ghw6u_143",
  "number": "awsui_number_1xupv_ghw6u_206",
  "circle": "awsui_circle_1xupv_ghw6u_222",
  "title": "awsui_title_1xupv_ghw6u_230",
  "active": "awsui_active_1xupv_ghw6u_258",
  "disabled": "awsui_disabled_1xupv_ghw6u_269",
  "enabled": "awsui_enabled_1xupv_ghw6u_279",
  "form": "awsui_form_1xupv_ghw6u_320",
  "form-header": "awsui_form-header_1xupv_ghw6u_325",
  "background": "awsui_background_1xupv_ghw6u_335",
  "form-header-content": "awsui_form-header-content_1xupv_ghw6u_347",
  "form-component": "awsui_form-component_1xupv_ghw6u_351",
  "hidden": "awsui_hidden_1xupv_ghw6u_365",
  "collapsed-steps": "awsui_collapsed-steps_1xupv_ghw6u_369",
  "collapsed-steps-hidden": "awsui_collapsed-steps-hidden_1xupv_ghw6u_374",
  "form-header-component-wrapper": "awsui_form-header-component-wrapper_1xupv_ghw6u_378",
  "form-header-component": "awsui_form-header-component_1xupv_ghw6u_378",
  "navigation-link": "awsui_navigation-link_1xupv_ghw6u_391",
  "navigation-link-item": "awsui_navigation-link-item_1xupv_ghw6u_392",
  "navigation-link-label": "awsui_navigation-link-label_1xupv_ghw6u_393",
  "navigation-link-active": "awsui_navigation-link-active_1xupv_ghw6u_397",
  "navigation-link-disabled": "awsui_navigation-link-disabled_1xupv_ghw6u_402",
  "cancel-button": "awsui_cancel-button_1xupv_ghw6u_406",
  "previous-button": "awsui_previous-button_1xupv_ghw6u_407",
  "primary-button": "awsui_primary-button_1xupv_ghw6u_408",
  "skip-to-button": "awsui_skip-to-button_1xupv_ghw6u_409",
  "action-buttons": "awsui_action-buttons_1xupv_ghw6u_413"
};
  