
    import './styles.scoped.css';
    export default {
  "root": "awsui_root_1wzqe_ggxic_113",
  "search-field": "awsui_search-field_1wzqe_ggxic_126",
  "input-wrapper": "awsui_input-wrapper_1wzqe_ggxic_132",
  "add-token": "awsui_add-token_1wzqe_ggxic_136",
  "tokens": "awsui_tokens_1wzqe_ggxic_143",
  "token-operator": "awsui_token-operator_1wzqe_ggxic_147",
  "property-editor": "awsui_property-editor_1wzqe_ggxic_151",
  "token-editor": "awsui_token-editor_1wzqe_ggxic_152",
  "property-editor-form": "awsui_property-editor-form_1wzqe_ggxic_156",
  "token-editor-form": "awsui_token-editor-form_1wzqe_ggxic_157",
  "property-editor-field-property": "awsui_property-editor-field-property_1wzqe_ggxic_160",
  "token-editor-field-property": "awsui_token-editor-field-property_1wzqe_ggxic_161",
  "property-editor-field-operator": "awsui_property-editor-field-operator_1wzqe_ggxic_164",
  "token-editor-field-operator": "awsui_token-editor-field-operator_1wzqe_ggxic_165",
  "property-editor-field-value": "awsui_property-editor-field-value_1wzqe_ggxic_168",
  "token-editor-field-value": "awsui_token-editor-field-value_1wzqe_ggxic_169",
  "property-editor-cancel": "awsui_property-editor-cancel_1wzqe_ggxic_172",
  "token-editor-cancel": "awsui_token-editor-cancel_1wzqe_ggxic_173",
  "property-editor-submit": "awsui_property-editor-submit_1wzqe_ggxic_176",
  "token-editor-submit": "awsui_token-editor-submit_1wzqe_ggxic_177",
  "property-editor-actions": "awsui_property-editor-actions_1wzqe_ggxic_180",
  "token-editor-actions": "awsui_token-editor-actions_1wzqe_ggxic_181",
  "custom-content-wrapper": "awsui_custom-content-wrapper_1wzqe_ggxic_199",
  "custom-control": "awsui_custom-control_1wzqe_ggxic_203",
  "input": "awsui_input_1wzqe_ggxic_132",
  "results": "awsui_results_1wzqe_ggxic_211",
  "token-trigger": "awsui_token-trigger_1wzqe_ggxic_217",
  "remove-all": "awsui_remove-all_1wzqe_ggxic_222",
  "token-label": "awsui_token-label_1wzqe_ggxic_223",
  "join-operation": "awsui_join-operation_1wzqe_ggxic_224",
  "custom-filter-actions": "awsui_custom-filter-actions_1wzqe_ggxic_225"
};
  