
    import './styles.scoped.css';
    export default {
  "calendar": "awsui_calendar_mgja0_fqbey_121",
  "awsui-motion-fade-in-0": "awsui_awsui-motion-fade-in-0_mgja0_fqbey_1",
  "root": "awsui_root_mgja0_fqbey_144",
  "focus-lock": "awsui_focus-lock_mgja0_fqbey_158",
  "trigger-wrapper": "awsui_trigger-wrapper_mgja0_fqbey_162",
  "trigger-flexbox": "awsui_trigger-flexbox_mgja0_fqbey_166",
  "calendar-container": "awsui_calendar-container_mgja0_fqbey_170",
  "one-grid": "awsui_one-grid_mgja0_fqbey_173",
  "calendar-header": "awsui_calendar-header_mgja0_fqbey_177",
  "calendar-header-months-wrapper": "awsui_calendar-header-months-wrapper_mgja0_fqbey_183",
  "calendar-header-month": "awsui_calendar-header-month_mgja0_fqbey_183",
  "calendar-next-month-btn": "awsui_calendar-next-month-btn_mgja0_fqbey_204",
  "calendar-prev-month-btn": "awsui_calendar-prev-month-btn_mgja0_fqbey_207",
  "first-grid": "awsui_first-grid_mgja0_fqbey_211",
  "second-grid": "awsui_second-grid_mgja0_fqbey_212",
  "date-and-time-container": "awsui_date-and-time-container_mgja0_fqbey_216",
  "date-and-time-wrapper": "awsui_date-and-time-wrapper_mgja0_fqbey_222",
  "footer": "awsui_footer_mgja0_fqbey_229",
  "has-clear-button": "awsui_has-clear-button_mgja0_fqbey_236",
  "footer-button-wrapper": "awsui_footer-button-wrapper_mgja0_fqbey_243",
  "icon-wrapper": "awsui_icon-wrapper_mgja0_fqbey_250",
  "label": "awsui_label_mgja0_fqbey_255",
  "label-enabled": "awsui_label-enabled_mgja0_fqbey_260",
  "label-text": "awsui_label-text_mgja0_fqbey_264",
  "label-token-nowrap": "awsui_label-token-nowrap_mgja0_fqbey_269",
  "mode-switch": "awsui_mode-switch_mgja0_fqbey_273",
  "dropdown": "awsui_dropdown_mgja0_fqbey_277",
  "dropdown-content": "awsui_dropdown-content_mgja0_fqbey_293",
  "start-date-input": "awsui_start-date-input_mgja0_fqbey_302",
  "start-time-input": "awsui_start-time-input_mgja0_fqbey_303",
  "end-date-input": "awsui_end-date-input_mgja0_fqbey_304",
  "end-time-input": "awsui_end-time-input_mgja0_fqbey_305",
  "validation-section": "awsui_validation-section_mgja0_fqbey_309",
  "validation-error": "awsui_validation-error_mgja0_fqbey_313",
  "clear-button": "awsui_clear-button_mgja0_fqbey_317",
  "apply-button": "awsui_apply-button_mgja0_fqbey_321",
  "cancel-button": "awsui_cancel-button_mgja0_fqbey_325",
  "calendar-aria-live": "awsui_calendar-aria-live_mgja0_fqbey_329"
};
  